#creation of pod and container push that into kube cluster
apiVersion: v1
kind: deployment
metadata:
  name: petclinic-app
spec:
  containers:
    - name: petclinic
      image: petclinic
      ports: 
         - containerPort: 8080

